In [1]:
import numpy as np #numpy kütüphanesini np takma adı ile projeye dagil ediyoruz

In [40]:
dizi=np.full((4,3),5) # 4 satır 3 sütunluk oluşan 5ten oluşan dizi
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
#yeni bir numpy dizisi olusturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [10]:
#olusturdugumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])

In [11]:
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [12]:
dizi=np.array([1,2,3])

In [13]:
dizi=np.array([1,2,3.14])

In [14]:
dizi.dtype#dizinin değişken türünü verir.numpy dizilerinde elemanların hepsi aynı türdendir

dtype('float64')

In [16]:
dizi=np.array([1,2,3.14],dtype=int)

**numpy ile farklı boyutlarda dizi oluşturma**

In [19]:
#bir boyutlu dizi oluşturma
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [20]:
birboyut

array([1, 2, 3, 4])

In [21]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**numpy yer tutucular**

In [22]:
np.zeros(7) #7 sıfırdan oluşan tek boyutlou dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((2,3),dtype=int) #sıfırdan oluşan 2 boyutlu int dizi olusturur

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.full((4,3),5) #5 sayısından oluşan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [30]:
np.arange(2,22,5) #bşlangiç,bitiş ve artış değerine göre dizi oluşturma

array([ 2,  7, 12, 17])

In [31]:
np.linspace(2,10,num=7) #başlangıç ve bitiş değeri aralığında belirtilen miktarda eşit aralık 

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [34]:
np.random.randint(0,10,5) # 0-10 aralığında rastgele 5 sayıdan oluşan bir boyutlu dizi

array([4, 2, 9, 4, 0])

In [35]:
np.random.randint(0,10,(5,2)) #0-10 araluğında 5*2 ratgele sayıdan oluşan 2 boyutlu dizi

array([[3, 8],
       [5, 5],
       [5, 7],
       [3, 7],
       [8, 2]])

**diziler ile ilgili işlemler**

In [36]:
#dizilerin eleman sayısıın öğrenmek için shape komutu kullanılır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,1,12]])
dizi.shape

(3, 4)

In [37]:
#ndim dizi boyutunu öğrenmek için kullanılır
dizi.ndim

2

In [38]:
#size dizideki toplam elemansayısını gösterir
dizi.size

12

In [39]:
dizi.itemsize #dizideki her bir elemanın bayt cinsinden değerini verir 

4